apiVersion: apps/v1
kind: Deployment
metadata:
  name: inclusiobot-deployment
  namespace: inclusiobot-canary
  labels:
    app: inclusiobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inclusiobot
  template:
    metadata:
      labels:
        app: inclusiobot
    spec:
      containers:
        - name: inclusiobot
          image: docker.io/anthonydmays/inclusiobot:latest
          imagePullPolicy: Always
          env:
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: inclusiobot-secrets
                  key: discord_bot_token
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: inclusiobot-secrets
                  key: discord_client_id
            - name: DISCORD_GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: inclusiobot-secrets
                  key: discord_guild_id
            - name: WP_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: inclusiobot-secrets
                  key: wp_bearer_token
            - name: WP_API_HOST
              valueFrom:
                secretKeyRef:
                  name: inclusiobot-secrets
                  key: wp_api_host
            - name: SKU_ROLES
              valueFrom:
                secretKeyRef:
                  name: inclusiobot-secrets
                  key: sku_roles
